# Generated by Django 4.0.5 on 2022-06-14 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0002_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(default='My Bio', max_length=500)),
                ('is_premium', models.TextField(default='no')),
                ('coins', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
                ('crop1', models.TextField(null=True)),
                ('crop2', models.TextField(null=True)),
                ('crop3', models.TextField(null=True)),
                ('crop4', models.TextField(null=True)),
                ('crop5', models.TextField(null=True)),
                ('crop6', models.TextField(null=True)),
                ('crop7', models.TextField(null=True)),
                ('crop8', models.TextField(null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('item', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemid', to='store.product')),
                ('owner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playerid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
