# Generated by Django 4.0.5 on 2022-06-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_bio_userprofile_is_premium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_premium',
            field=models.CharField(choices=[('NO', 'NO'), ('YES', 'YES')], max_length=3),
        ),
    ]
