# Generated by Django 4.0.5 on 2022-06-14 18:06

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profile_coins_profile_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='crop1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='crop2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='crop3',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='crop4',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='crop5',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='crop6',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='crop7',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='crop8',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='inventory',
            field=picklefield.fields.PickledObjectField(editable=False, null=True),
        ),
    ]
