# Generated by Django 4.0.5 on 2022-06-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='coins',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
