# Generated by Django 4.0.5 on 2022-06-20 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_profile_crop1_alter_profile_crop2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='crop1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='crop2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='crop3',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='crop4',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='crop5',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='crop6',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='crop7',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='crop8',
        ),
    ]
