# Generated by Django 4.0.5 on 2022-07-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_remove_profile_crop1_remove_profile_crop2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='coins',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
