# Generated by Django 4.0.5 on 2022-07-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_alter_profile_coins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='coins',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
