# Generated by Django 4.0.5 on 2022-06-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_sell_price_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='produces',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
