# Generated by Django 4.0.5 on 2022-06-20 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop1', models.TextField(blank=True, null=True)),
                ('crop2', models.TextField(blank=True, null=True)),
                ('crop3', models.TextField(blank=True, null=True)),
                ('crop4', models.TextField(blank=True, null=True)),
                ('crop5', models.TextField(blank=True, null=True)),
                ('crop6', models.TextField(blank=True, null=True)),
                ('crop7', models.TextField(blank=True, null=True)),
                ('crop8', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farm', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
