# Generated by Django 4.0.5 on 2022-06-25 09:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop1', models.TextField(blank=True, null=True)),
                ('crop1_harvest_time', models.DateTimeField(blank=True, null=True)),
                ('crop2', models.TextField(blank=True, null=True)),
                ('crop2_harvest_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('crop3', models.TextField(blank=True, null=True)),
                ('crop3_harvest_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('crop4', models.TextField(blank=True, null=True)),
                ('crop4_harvest_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('crop5', models.TextField(blank=True, null=True)),
                ('crop5_harvest_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('crop6', models.TextField(blank=True, null=True)),
                ('crop6_harvest_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('crop7', models.TextField(blank=True, null=True)),
                ('crop7_harvest_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('crop8', models.TextField(blank=True, null=True)),
                ('crop8_harvest_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farm', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
