# Generated by Django 4.0.5 on 2022-06-25 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_sell_price_alter_product_price'),
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='crop1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crop1', to='store.product'),
        ),
    ]
