# Generated by Django 4.0.5 on 2022-06-20 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_farm_crop1_plant_time_farm_crop2_plant_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farm',
            old_name='crop1_plant_time',
            new_name='crop1_harvest_time',
        ),
        migrations.RenameField(
            model_name='farm',
            old_name='crop2_plant_time',
            new_name='crop2_harvest_time',
        ),
        migrations.RenameField(
            model_name='farm',
            old_name='crop3_plant_time',
            new_name='crop3_harvest_time',
        ),
        migrations.RenameField(
            model_name='farm',
            old_name='crop4_plant_time',
            new_name='crop4_harvest_time',
        ),
        migrations.RenameField(
            model_name='farm',
            old_name='crop5_plant_time',
            new_name='crop5_harvest_time',
        ),
        migrations.RenameField(
            model_name='farm',
            old_name='crop6_plant_time',
            new_name='crop6_harvest_time',
        ),
        migrations.RenameField(
            model_name='farm',
            old_name='crop7_plant_time',
            new_name='crop7_harvest_time',
        ),
        migrations.RenameField(
            model_name='farm',
            old_name='crop8_plant_time',
            new_name='crop8_harvest_time',
        ),
    ]
