# Generated by Django 4.0.5 on 2022-06-25 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_sell_price_alter_product_price'),
        ('farm', '0002_alter_farm_crop1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='crop2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crop2', to='store.product'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='crop3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crop3', to='store.product'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='crop4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crop4', to='store.product'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='crop5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crop5', to='store.product'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='crop6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crop6', to='store.product'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='crop7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crop7', to='store.product'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='crop8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crop8', to='store.product'),
        ),
    ]
