# Generated by Django 4.0.5 on 2022-06-20 18:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0003_rename_crop1_plant_time_farm_crop1_harvest_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='crop1_harvest_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
