# Generated by Django 4.0.5 on 2022-06-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0004_alter_farm_crop1_harvest_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='crop1_harvest_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
